name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 20
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew shadowJar
      - uses: docker/build-push-action@v5
        with:
          push: false
          tags: the-mind:latest
          context: .
          outputs: type=tar,dest=/tmp/the-mind.tar
      - uses: actions/upload-artifact@v4
        with:
          name: app-image
          path: /tmp/the-mind.tar
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-image
          path: /tmp/the-mind.tar
      - run: tar -czf the-mind.tar.gz the-mind.tar
      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: /tmp/the-mind.tar.gz
          target: ~/projects/the-mind/
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            ~/projects/the-mind/deploy-tar.sh
